#!/usr/bin/env bash
usage() {
cat << EOF
Usage: $0 [-h] [-c <build_configuration>] <scheme> [<output_directory>]
    options:
        -c    Build configuration. Defaults to "Release".
        -h    Print this message.
    Build xcframework for a given scheme.
    Output directory defaults to working directory if not provided.
EOF
}

build_xcframework() {
    local scheme=$1
    local config=$2
    local output_dir=$3

    local mach_o_type="staticlib"
    local destinations=("generic/platform=iOS" "generic/platform=iOS Simulator")
    local framework_args=()
    local framework_name
    [[ $config = "Release" ]] && framework_name="${scheme}" || framework_name="${scheme}.${config}"
    for destination in "${destinations[@]}"; do
        local platform="${destination#*=}"
        platform="${platform/ /_}"
        local archive_path="${output_dir}/${framework_name}-${platform}.xcarchive"
        xcodebuild archive \
                   -scheme "${scheme}" \
                   -configuration "${config}" \
                   -destination "${destination}" \
                   -archivePath "${archive_path}" \
                   SKIP_INSTALL=NO \
                   BUILD_LIBRARY_FOR_DISTRIBUTION=YES\
                   MACH_O_TYPE="${mach_o_type}" \
                   CODE_SIGNING_ALLOWED=NO
        if (( $? > 0)); then
            printf "Failed to archive for %s\n" "${destination}" >&2
            return 1
        fi
        framework_args+=(-framework "${archive_path}/Products/Library/Frameworks/${scheme}.framework")
    done
    # Combine into xcframework
    xcodebuild -create-xcframework \
               "${framework_args[@]}" \
               -output "${output_dir}/${framework_name}.xcframework"
    if (( $? > 0)); then
        printf "Failed to create xcframework.\n" >&2
        return 1
    fi
}

main() {
    local build_config="Release"
    while getopts "hc:" opt; do
        case "$opt" in
            h) usage; return ;;
            c) build_config="$OPTARG" ;;
            *) usage >&2; return 1 ;;
        esac
    done

    shift $((OPTIND - 1))
    local scheme=$1
    local output_dir="${2:-.}"

    if [[ -z "$scheme" ]]; then
        printf "%s failed\nError: %s\n\n" "$0" "Missing scheme." >&2
        usage >&2
        return 1
    fi

    build_xcframework "$scheme" "$build_config" "$output_dir"
}

main "$@"
